<?php

/**
 * @file
 * Contains migrate_csv.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_csv_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_csv module.
    case 'help.page.migrate_csv':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('importation fichier csv des membres et partenaires') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function migrate_csv_theme() {
  return [
    'migrate_csv' => [
      'render element' => 'children',
    ],
  ];
}
